"""add deployment events

Revision ID: d81e7fed3d81
Revises: dc39ab989787
Create Date: 2026-04-29 19:20:58.882147

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd81e7fed3d81'
down_revision: Union[str, None] = 'dc39ab989787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('from_version', sa.String(), nullable=True),
    sa.Column('to_version', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployment_events_model_created_at', 'deployment_events', ['model_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_deployment_events_model_name'), 'deployment_events', ['model_name'], unique=False)
    op.alter_column('eval_runs', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('job_records', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('model_versions', 'runtime_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('model_versions', 'metadata_',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'metadata_',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('model_versions', 'runtime_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('job_records', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('eval_runs', 'config_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_deployment_events_model_name'), table_name='deployment_events')
    op.drop_index('ix_deployment_events_model_created_at', table_name='deployment_events')
    op.drop_table('deployment_events')
    # ### end Alembic commands ###
